package client.ui;

import client.AccessWindow;
import client.Client;
import client.Sharing;
import commons.Content;
import commons.ContentType;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rp wadhwani
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    ClientFrame clientFrame;
    Client client = null;
    String ip;
    int port;

    JMenuBar menuBar;
    JMenu menu;
    JMenu menu1;
    JMenu menu2;
    JMenu menu3;
    JMenuItem menuItem;
    JMenuItem menuItem1;
    JMenuItem menuItem2;
    JMenuItem menuItem3;
    JMenuItem menuItem4;
    JMenuItem menuItem5;
    JMenuItem menuItem6;

    JMenuItem menuItem7;
    JMenuItem menuItem8;
    JMenuItem menuItem9;
    boolean isOpen = true;

    private String myName;
    private static final String ICON = "E:\\TeamViewer_Logo_512x512.png";
    private static final String APP_TITLE = "TeamViewer";

    {

        try {
            myName = InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            System.out.println("ex in cons mainpanel" + ex);
        }

    }

    public MainPanel(String ip, int port, ClientFrame clientFrame) {
        initComponents();
        setVisible(true);
        this.setSize(510, 676);
        this.clientFrame = clientFrame;
        this.ip = ip;
        this.port = port;
        jLabel1.setText(jLabel1.getText() + myName);
        initJMenuBar();
    }

    public void initJMenuBar() {
        menuBar = new JMenuBar();

        //Build the first menu.
        menu = new JMenu("Connection");
        menu1 = new JMenu("Extras");
        menu2 = new JMenu("Help");
        menu3 = new JMenu("Feedback");
        menuBar.add(menu);
        menuBar.add(menu1);
        menuBar.add(menu2);
        menuBar.add(menu3);
        menuItem = new JMenuItem("Invite a partner");
        menuItem1 = new JMenuItem("Open User Management");
        menuItem2 = new JMenuItem("Open Design & Deloy");
        menuItem3 = new JMenuItem("Exit TeamViewer");
        menuItem4 = new JMenuItem("Options");
        menuItem5 = new JMenuItem("Activate license");
        menuItem6 = new JMenuItem("Buy license");

        menuItem7 = new JMenuItem("TeamViewer Website");
        menuItem8 = new JMenuItem("TeamViewer Community");
        menuItem9 = new JMenuItem("TeamViewer Web Help");

        menu.add(menuItem);
        menu.add(menuItem1);
        menu.add(menuItem2);
        menu.add(menuItem3);

        menu1.add(menuItem4);
        menu1.add(menuItem5);
        menu1.add(menuItem6);
        menu2.add(menuItem7);
        menu2.add(menuItem8);
        menu2.add(menuItem9);

        clientFrame.setJMenuBar(menuBar);
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (sharing.chatPage != null && isOpen) {
                    sharing.chatPage.setVisible(true);
                    isOpen = false;
                } else {
                    JOptionPane.showMessageDialog(null, "Chat Frame is already open ");
                }
            }
        });
        menuItem.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShare = new javax.swing.JButton();
        btnAccess = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));

        btnShare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/share.png"))); // NOI18N
        btnShare.setText("Share");
        btnShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShareActionPerformed(evt);
            }
        });

        btnAccess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/access.png"))); // NOI18N
        btnAccess.setText("Access");
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Java06\\ProjectFinal\\TeamViewerClient\\src\\images\\images.jpg")); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Computer Name : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShare, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShare, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed

        String s = JOptionPane.showInputDialog(null, "Enter access code:");
        System.out.println(s);
        if (s != null && !s.equals("")) {
            client = new Client(ip, port, this);
            client.sendContent(new Content(ContentType.NAME, myName));
            client.sendContent(new Content(ContentType.ACCESSCODE, Integer.parseInt(s)));
            Content content = client.receiveContent();
            System.out.println("read Content " + content);
//        client.close();
            if (content == null) {
                menuItem.setEnabled(true);
                System.out.println("in if");
                aw = new AccessWindow(client);
                System.out.println("aw initialozed : client " + client);
                aw.setVisible(true);
                aw.start();
                System.out.println("aw started");
            } else {
                JOptionPane.showMessageDialog(null, "Could not connect", "Something went wrong!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("enter proper access code");
        }
    }//GEN-LAST:event_btnAccessActionPerformed

    private void btnShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShareActionPerformed
        new Thread(() -> {
            client = new Client(ip, port, this);
            client.sendContent(new Content(ContentType.NAME, myName));
            client.sendContent(null);
            Content content = client.receiveContent();
            if (content != null) {
                System.out.println("in if of shareButton");
                int code = (Integer) content.getContent();
                JOptionPane.showMessageDialog(null, "Your code is " + code);
            }
            content = client.receiveContent();
            menuItem.setEnabled(true);
            System.out.println("content read" + content);
            if (content == null) {
                sharing = new Sharing(client);
                System.out.println("after init sharing :");

                sharing.sendImagesToServer();
                sharing.receiveData();
                sharing.isSharing = true;
                System.out.println("sharing started");
            }
        }).start();
    }//GEN-LAST:event_btnShareActionPerformed
    private AccessWindow aw = null;

    private Sharing sharing = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccess;
    private javax.swing.JButton btnShare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
